# team names

teams = ['*Commerce VAN*',
'*Core Data - UA*',
'*Fulfillment*',
'*Reporting*',
'*Routing*',
'*TPD Engineering Core*',
'*Core Data - DEX*',
'*Core Data - Rules*',
'*Dev Center Engineering*',
'*Fulfillment US*',
'*Fulfillment Monitor*',
'*Acumatica Adaptor*',
'*MAPADOC Cloud*',
'*MAPADOC Sage 100 & Sage 500*',
'*MAPADOC Sage X3*',
'*NetSuite*',
'*Parcel Service*',
'*QuickBooks*',
'*System Automation Framework*',
'*TPDE - Cory*',
'*TPDE - LaMoine*',
'*Transformation*',
'*Workflow*',]
